# Generated by Django 5.0 on 2024-01-17 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('balance', models.FloatField(default=0)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.budget')),
            ],
        ),
    ]
