# Generated by Django 5.0 on 2024-01-17 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetGroup',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.budget')),
            ],
        ),
    ]
