# Generated by Django 5.0 on 2024-01-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_budget_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('budget_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.budgetgroup')),
            ],
        ),
    ]
