# Generated by Django 5.0.1 on 2024-01-20 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_budget_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetcategory',
            options={'verbose_name': 'Budget Category', 'verbose_name_plural': 'Budget Categories'},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('bank_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bankaccount')),
            ],
        ),
    ]
