# Generated by Django 5.0.2 on 2024-03-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_unlink_budget_from_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance',
        ),
    ]
